### ISSUE TITLE
Durduruldu

### ISSUE THREAD

**Issue by enigamtr** [Include-sys/GUI-for-GoodbyeDPI#1]
Başlata bastığım anda log bölümünde durduruldu yazıyor ve uygulama çalışmıyor. Çözüm var mı?

**Comment by Include-sys** [comment]
Merhaba,

Uzun zamandır geliştirmiyorum yazılımı ama şu linkteki forkunu kullanabilirsiniz.

https://github.com/cheytacllc/GUI-for-GoodbyeDPI

Veya tamamen Simplecrypt kullanabilirsiniz.(dnscrypt)
