### ISSUE TITLE
suggest to add option about 'service_remove when exit'

### ISSUE THREAD

**Issue by hong620** [Include-sys/GUI-for-GoodbyeDPI#3]
GoodbyeDPI seems Only deliver Batch Script as Remove they're service method.

> service_remove.cmd

`@ECHO OFF
echo This script should be run with administrator privileges.
echo Right click - run as administrator.
echo Press any key if you're running it as administrator.
pause
sc stop "GoodbyeDPI"
sc delete "GoodbyeDPI"
sc stop "WinDivert1.4"
sc delete "WinDivert1.4"`

those GoodbyeDPI and WinDivert1.4 services keep running on background even in after the app closed. it's known issue but there's possible to add option on GUI for automate revert services when close the GUI-for-GoodbyeDPI?

btw current 0.1.5 work well with this GUI.

**Comment by Include-sys** [comment]
Hello,

I wasn't able to update it for a while, I am aware of It has issues and lack of some features, will give a huge update soon.

Thank you for feedback.

Regards.

**Comment by Include-sys** [comment]
I added, It will execute that script every time quit. There is a problem uploading files on GitHub at the moment, will release as soon as I can.

**Comment by hong620** [comment]
@Include-sys 

I've Tested in Both 'Minimize to Tray' tick and untick.

seems 'Minimize to Tray' functional seems broken, application quit is not finished in general.

not shown on tray, still both GUI and WinDivert64 for GoodByeDP activated in background.
so naturally those service revert script doesn't excute properly.
(cause i can't click the exit the GUI from tray, can't bring window of app either)

i guess results in 'Minimize to Tray' tick/untick enviorments are little diffirent but anyway base functional is broken.
so.. i think fix those issues before investigate and test this one seems reasonable.

in 1.0.2 test, it looks quit the GUI properly, so possible to remove services and application in manual way.

**Comment by Include-sys** [comment]
Fixed.

**Comment by hong620** [comment]
tray problem seems fixed but WinDivert64.sys is still Handling by system.
remove WinDivert64.sys is still unavariable until manually run remove script.

i've test as administrator privileges, this function is working as default? or have to activate somewhere in options?

on me, GUI automatly recorgnize my system language(korean) and show it as recent korean language option menus but i can't find any option tickbox about 'remove services when exit' related things.
only 4 tickbox shown on option menu.

![default](https://user-images.githubusercontent.com/12625315/53301652-d4547500-3898-11e9-8b4d-7b58c4b03df8.PNG)

there's any method to forcing it to output default english language?
it only shown as my system language(korea) so i can't much test further for checking proper causes.

GUI 1.0.2 with gbDPI 0.1.5 still working well so don't need to rush on this issue i think. 🤔 

anyway thx for working for it.

**Comment by Include-sys** [comment]
It execute service_remove script automatically when you stop service. Actually I forgot to add it to close event. :) About language I probably make it in future.

And can you show me where exactly you see windivert service?

**Comment by hong620** [comment]
![default](https://user-images.githubusercontent.com/12625315/53307583-49499e00-38dd-11e9-98bd-d1364c853b4f.PNG)

simply can check it trough delete it.
it's still handling after stop the service in the GUI, even in after fully quit the GUI.

i've record video of it for explanation.

[https://gfycat.com/ActualBeautifulAplomadofalcon](https://gfycat.com/ActualBeautifulAplomadofalcon)

also, how 'bout considering 'run the remove service script' option as 'when quit the GUI app' ?
would be enough on this time for fit in some user's purpose. ~~delete evidence before wife checking it~~🗑
