### ISSUE TITLE
 Can not run on a specific path

### ISSUE THREAD

**Issue by devilduo** [Include-sys/GUI-for-GoodbyeDPI#5]
Dear Developer

Can not run on a specific path

ex ) C:\Program Files\GoodByeDPI_GUI_64Bit  - don`t running
       C:\Program_Files\GoodByeDPI_GUI_64Bit  - running

Does not run if there are spaces in the path

**Comment by Include-sys** [comment]
Hello,

Thank you for feedback, I will fix it.

Regards.

**Comment by Include-sys** [comment]
Fixed.

https://github.com/Include-sys/GUI-for-GoodbyeDPI/releases/tag/v1.0.3
