### ISSUE TITLE
I can't run with v.1.0.3

### ISSUE THREAD

**Issue by YesikaDaria** [Include-sys/GUI-for-GoodbyeDPI#7]
![k-1](https://user-images.githubusercontent.com/47796431/53047408-b15f4500-34d5-11e9-8092-83609f56ec13.png)

(Problem 1) When I try to start DPI that message keep comes up.
(I've already updated KB3033929 Update and others)
This is the first problem I have...

(Problem 2) And for the second thing is...
The error "Error opening filter: the system cannot find the file specified"
comes out.
I see those messages when I changed the folder name different when problem 1 occurs

Uh...
If the located folders name is "A", then the Problem 1 occurs
If the located folders name is "B" then the Problem 2 occurs

But v.1.0.2 is still alive (I can still use v.1.0.2 with out any errors)

**Comment by Include-sys** [comment]
Hello,

First problem occurs because of GoodbyeDPI, try to use @ValdikSS version. I will update it as soon as I find enough time to do.

Regards.

**Comment by YesikaDaria** [comment]
With every words that I know, Thank you. thank you very much.

**Comment by Include-sys** [comment]
I hope It's fixed. There is a problem uploading files on GitHub at the moment, will release as soon as I can.
